[32m2023-01-05 18:32:40 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 7d1f7142-4eb9-49c3-9020-13d9bc47dd2a - 2736 - LOGS_CAPTURED - Started capturing logs in process (pid: 2736).
[32m2023-01-05 18:32:40 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 7d1f7142-4eb9-49c3-9020-13d9bc47dd2a - 2736 - stg_payments - STEP_START - Started execution of step "stg_payments".
[32m2023-01-05 18:32:40 +0000[0m - dagster - [34mDEBUG[0m - __ASSET_JOB - 7d1f7142-4eb9-49c3-9020-13d9bc47dd2a - 2736 - stg_payments - STEP_OUTPUT - Yielded output "result" of type "SQL". (Type check passed).
[32m2023-01-05 18:32:40 +0000[0m - dagster - [34mERROR[0m - [31m__ASSET_JOB - 7d1f7142-4eb9-49c3-9020-13d9bc47dd2a - 2736 - stg_payments - STEP_FAILURE - Execution of step "stg_payments" failed.

dagster._core.errors.DagsterExecutionHandleOutputError: Error occurred while handling output "result" of step "stg_payments"::

duckdb.Error: Invalid Error: HTTP HEAD error on 'http://localhost:4566/datalake/stg_payments.parquet' (Error code 2)

Stack Trace:
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster/_core/execution/plan/utils.py", line 56, in op_execution_error_boundary
    yield
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster/_utils/__init__.py", line 458, in iterate_with_context
    next_output = next(iterator)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_step.py", line 626, in _gen_fn
    gen_output = output_manager.handle_output(output_context, output.value)
  File "/workspace/modern-datastack/cloned/dagster-poor-mans-data-lake/jaffle/duckpond.py", line 84, in handle_output
    self.duckdb.query(
  File "/workspace/modern-datastack/cloned/dagster-poor-mans-data-lake/jaffle/duckpond.py", line 56, in query
    result = db.query(sql_to_string(select_statement))
[0m
